language: node_js
node_js:
  - 12.14.1
cache:
  directories:
    - node_modules
before_script:
  - cd app  
  - npm install
  - npm install -g codecov
  - npm run express &
script:
  - npm run test:unit
  - codecov