language: node_js
node_js:
  - 12.14.1
cache:
  directories:
    - node_modules
before_script:
  - cd app  
  - npm install
script:
  - npm run test:unit
after_success:
  - codecov -t c87a5e6c-9f16-49e7-883b-75f4b8026ea0