language: node_js
node_js:
- 12.14.1
cache:
  directories:
  - node_modules
before_script:
- cd app
- npm install
- npm install -g codecov
script:
- npm run test:unit
- codecov
- npm run build
before_deploy:
- openssl aes-256-cbc -K $encrypted_aedd9205a433_key -iv $encrypted_aedd9205a433_iv
  -in python-portland-pollution-fdbfcd931162.json.enc -out python-portland-pollution-fdbfcd931162.json
  -d
deploy:
  skip_cleanup: true
  provider: gae
  keyfile: python-portland-pollution-fdbfcd931162.json
  project: python-portland-pollution
before_install:
- cd app
- openssl aes-256-cbc -K $encrypted_767105206995_key -iv $encrypted_767105206995_iv
  -in passwords.json.enc -out passwords.json -d
- cd ..
