language: node_js
node_js:
- 12.14.1
cache:
  directories:
  - node_modules
before_install:
- openssl aes-256-cbc -K $encrypted_e894514096c9_key -iv $encrypted_e894514096c9_iv
  -in python-portland-pollution-fdbfcd931162.json.enc -out python-portland-pollution-fdbfcd931162.json
  -d
before_script:
- cd app
- npm install
- npm install -g codecov
script:
- npm run test:unit
- codecov
- npm run build
deploy:
  skip_cleanup: true
  provider: gae
  keyfile: python-portland-pollution-fdbfcd931162.json
  project: python-portland-pollution
  on:
    branch: master
