language: node_js
node_js:
- 12.14.1
cache:
  directories:
  - node_modules
before_install:
- bash ./travis_decrypt.sh
before_script:
- cd app
- npm install
- npm install -g codecov
script:
- npm run test:unit
- codecov
- npm run build
deploy:
  skip_cleanup: true
  provider: gae
  keyfile: python-portland-pollution-fdbfcd931162.json
  project: python-portland-pollution
  on:
    branch: master
